# Generated by Django 3.2.3 on 2022-03-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masomoyangu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Notes'},
        ),
    ]
