# Generated by Django 3.2.3 on 2022-03-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masomoyangu', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
    ]
